In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
import plotly.offline as px

In [2]:
data = pd.read_csv(r"C:\Users\shobh\OneDrive\Attachments\Documents\Desktop\py\Mobiles Dataset (2025).csv", encoding = 'latin-1')

df = pd.DataFrame(data)

In [3]:
shape = df.shape

print("Data Set have ",shape[0]," rows and total",shape[1],"column")

print("\n All Coloumns :\n",df.columns)

print(type(df))

print(df.info())

print(df.describe)

Data Set have  930  rows and total 15 column

 All Coloumns :
 Index(['Company Name', 'Model Name', 'Mobile Weight', 'RAM', 'Front Camera',
       'Back Camera', 'Processor', 'Battery Capacity', 'Screen Size',
       'Launched Price (Pakistan)', 'Launched Price (India)',
       'Launched Price (China)', 'Launched Price (USA)',
       'Launched Price (Dubai)', 'Launched Year'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Company Name               930 non-null    object
 1   Model Name                 930 non-null    object
 2   Mobile Weight              930 non-null    object
 3   RAM                        930 non-null    object
 4   Front Camera               930 non-null    object
 5   Back Camera                930 non-null    object
 6   Processor                  930 non-null    object
 7   Battery Capacity           930 non-null    object
 8   Screen Size                930 non-null    object
 9   Launched Price (Pakistan)  930 non-null    object
 10  Launched Price (India)     930 non-null    object
 11  Launched Price (China)     930 non-null    object
 12  Launched Price (USA)       930 non-null    object
 13  Launched Price (Dubai)     930 non-null    object
 14  Launched Year              930 non-null    int64
dtypes: int64(1), object(14)
memory usage: 109.1+ KB
None
<bound method NDFrame.describe of     Company Name            Model Name Mobile Weight   RAM     Front Camera  \
0          Apple       iPhone 16 128GB          174g   6GB             12MP
1          Apple       iPhone 16 256GB          174g   6GB             12MP
2          Apple       iPhone 16 512GB          174g   6GB             12MP
3          Apple  iPhone 16 Plus 128GB          203g   6GB             12MP
4          Apple  iPhone 16 Plus 256GB          203g   6GB             12MP
..           ...                   ...           ...   ...              ...
925         Poco          Pad 5G 128GB          571g   8GB              8MP
926         Poco          Pad 5G 256GB          571g   8GB              8MP
927      Samsung  Galaxy Z Fold6 256GB          239g  12GB  10MP, 4MP (UDC)
928      Samsung  Galaxy Z Fold6 512GB          239g  12GB  10MP, 4MP (UDC)
929      Samsung    Galaxy Z Fold6 1TB          239g  12GB  10MP, 4MP (UDC)

    Back Camera            Processor Battery Capacity  Screen Size  \
0          48MP           A17 Bionic         3,600mAh   6.1 inches
1          48MP           A17 Bionic         3,600mAh   6.1 inches
2          48MP           A17 Bionic         3,600mAh   6.1 inches
3          48MP           A17 Bionic         4,200mAh   6.7 inches
4          48MP           A17 Bionic         4,200mAh   6.7 inches
..          ...                  ...              ...          ...
925         8MP  Snapdragon 7s Gen 2        10,000mAh  12.1 inches
926         8MP  Snapdragon 7s Gen 2        10,000mAh  12.1 inches
927        50MP   Snapdragon 8 Gen 3          4400mAh   7.6 inches
928        50MP   Snapdragon 8 Gen 3          4400mAh   7.6 inches
929        50MP   Snapdragon 8 Gen 3          4400mAh   7.6 inches

    Launched Price (Pakistan) Launched Price (India) Launched Price (China)  \
0                 PKR 224,999             INR 79,999              CNY 5,799
1                 PKR 234,999             INR 84,999              CNY 6,099
2                 PKR 244,999             INR 89,999              CNY 6,499
3                 PKR 249,999             INR 89,999              CNY 6,199
4                 PKR 259,999             INR 94,999              CNY 6,499
..                        ...                    ...                    ...
925                PKR 66,220             INR 23,999              CNY 2,099
926                PKR 71,220             INR 25,999              CNY 2,299
927               PKR 604,999            INR 164,999                ¥13,999
928               PKR 544,999            INR 176,999             CNY 15,999
929             Not available            INR 200,999            CNY 17,999

    Launched Price (USA) Launched Price (Dubai)  Launched Year
0                USD 799              AED 2,799           2024
1                USD 849              AED 2,999           2024
2                USD 899              AED 3,199           2024
3                USD 899              AED 3,199           2024
4                USD 949              AED 3,399           2024
..                   ...                    ...            ...
925              USD 280              AED 1,029           2024
926              USD 300              AED 1,099           2024
927            USD 1,899              AED 7,199           2024
928             USD 1719              AED 7,699           2024
929            USD 2,259              AED 8,699           2024

[930 rows x 15 columns]>

In [4]:
print(df.info())


print(df.isnull().sum())

print(df.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Company Name               930 non-null    object
 1   Model Name                 930 non-null    object
 2   Mobile Weight              930 non-null    object
 3   RAM                        930 non-null    object
 4   Front Camera               930 non-null    object
 5   Back Camera                930 non-null    object
 6   Processor                  930 non-null    object
 7   Battery Capacity           930 non-null    object
 8   Screen Size                930 non-null    object
 9   Launched Price (Pakistan)  930 non-null    object
 10  Launched Price (India)     930 non-null    object
 11  Launched Price (China)     930 non-null    object
 12  Launched Price (USA)       930 non-null    object
 13  Launched Price (Dubai)     930 non-null    object
 14  Launched Year              930 non-null    int64
dtypes: int64(1), object(14)
memory usage: 109.1+ KB
None
Company Name                 0
Model Name                   0
Mobile Weight                0
RAM                          0
Front Camera                 0
Back Camera                  0
Processor                    0
Battery Capacity             0
Screen Size                  0
Launched Price (Pakistan)    0
Launched Price (India)       0
Launched Price (China)       0
Launched Price (USA)         0
Launched Price (Dubai)       0
Launched Year                0
dtype: int64
15

In [5]:
df.sample()

,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (Pakistan),Launched Price (India),Launched Price (China),Launched Price (USA),Launched Price (Dubai),Launched Year
534,Xiaomi,Xiaomi 14 256GB,189g,12GB,32MP,50MP (Main) + 50MP (Ultra-wide),Snapdragon 8 Gen 3,"4,610mAh",6.36 inches,"PKR 169,999","INR 74,999","CNY 3,999",USD 699,"AED 2,899",2023

In [6]:
price = df[['Launched Price (Pakistan)', 'Launched Price (China)','Launched Price (USA)','Launched Price (Dubai)']]

price.info()

#Extracting currency symbols


price = df[['Launched Price (Pakistan)', 'Launched Price (China)','Launched Price (USA)','Launched Price (Dubai)']]



final = price.apply(lambda x:  str(x).split(" ")[3])

final

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 4 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Launched Price (Pakistan)  930 non-null    object
 1   Launched Price (China)     930 non-null    object
 2   Launched Price (USA)       930 non-null    object
 3   Launched Price (Dubai)     930 non-null    object
dtypes: object(4)
memory usage: 29.2+ KB

Launched Price (Pakistan)
Launched Price (China)
Launched Price (USA)
Launched Price (Dubai)
dtype: object

In [7]:
df.sample()

,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (Pakistan),Launched Price (India),Launched Price (China),Launched Price (USA),Launched Price (Dubai),Launched Year
770,Infinix,Note 40 Pro,190g,12GB,32MP,108MP,MediaTek Dimensity 8100,"5,000mAh",6.78 inches,"PKR 59,999","INR 22,999","CNY 2,199",USD 329,"AED 1,199",2024

In [21]:
price = df['Launched Price (India)'].apply(lambda x : str(x))

price

final = df['Launched Price (India)'].apply(lambda x : x.split(" ")[1])

final 


slot = df['Launched Price (India)'].apply(lambda x : x.remove(","))

slot
# price = df['Launched Price (India)'].astype(int)

# print(converted)

AttributeError: 'str' object has no attribute 'remove'

In [22]:
p = "Python"

px = p.remove("y")

px

AttributeError: 'str' object has no attribute 'remove'